# Site settings
title: SlicerCMF
email: https://discourse.slicer.org/c/community/slicercmf
description: > # this means to ignore newlines until "baseurl:"
  Open-source image analysis software for Dental Research in 3D Slicer
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: DCBIA-OrthoLab

# Build settings
markdown: kramdown
